authorizationservice:
  image: yurykiryla/authorizationservice
  mem_limit: 1073741824
  ports:
    - "8901:8901"
  environment:
    ENCRYPT_KEY: "IMSYMMETRIC"
    CONFIGSERVER_URI: "http://18.220.211.153/:8888"